language: go
go:
  - 1.5.1
  - 1.4.3
  - 1.3.3

sudo: false

before_install:
  - go get golang.org/x/tools/cmd/vet
  - go get github.com/golang/lint/golint

install: true

script:
  - go vet -x ./...
  - $HOME/gopath/bin/golint ./...
  - go run .tools/validate.go -range ${TRAVIS_COMMIT_RANGE}
  
